OPENAI_API_KEY="sk-hyJTnzFaDQAbuAP_VDgyj54U7srqKBoQr0TOdOyBd-T3BlbkFJPKwNrHE_bEWRRro1zK8UjVfh2I0uue6CsAS0xD3i8A"
COHERE_API_KEY="HR9Oo1rvbnAhNueXgp5u5bVC90pZA0cDkIojsbR8"
GROQ_API_KEY="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"

