OPENAI_API_KEY="sk-J_c13naGOo-XcyleaRXgDF7NYA9Ycqc_05mmGdWBwDT3BlbkFJ_-jGwM6eVr5EARi_NQmTqdF0SHPKpgyiROeBuxytgA"
COHERE_API_KEY="HR9Oo1rvbnAhNueXgp5u5bVC90pZA0cDkIojsbR8"
GROQ_API_KEY="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"

